1. Create a vector with values ranging from 10 to 49.

In [1]:
import numpy as np

vector = np.arange(10, 50)
print("vector ranging 10-49:", vector)

vector ranging 10-49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3x3 matrix with values ranging from 0 to 8.

In [2]:
mat_3_X_3 = np.arange(9).reshape(3, 3)
print("Matrix", mat_3_X_3)

Matrix [[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3x3 identity matrix.

In [3]:

identity_matrix = np.eye(3)
print("Identity_Mat", identity_matrix)

Identity_Mat [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a 10x10 array with random values and find the minimum and maximum values.

In [7]:
array_10x10 = np.random.random((10, 10))
min_value = np.min(array_10x10)
max_value = np.max(array_10x10)
print("10x10 Array:", array_10x10)
print("Min:", min_value)
print("Max:", max_value)

10x10 Array: [[0.63755534 0.60871273 0.77059358 0.21422546 0.84670092 0.77299302
  0.64968927 0.39356672 0.63634177 0.93052415]
 [0.45579196 0.18605912 0.9710736  0.91030642 0.56505612 0.23238719
  0.90831364 0.90990716 0.09702616 0.641218  ]
 [0.93250515 0.58852541 0.43292021 0.77733029 0.12549088 0.94125988
  0.47279973 0.71071314 0.72594611 0.03535292]
 [0.46181662 0.79232299 0.22550009 0.54381404 0.5601703  0.93293484
  0.11688463 0.82459226 0.09041596 0.14332278]
 [0.95520805 0.21794393 0.64285437 0.53089538 0.32181806 0.9661678
  0.37007258 0.77399633 0.41432002 0.5537085 ]
 [0.07361794 0.01357678 0.74196386 0.89325102 0.38869406 0.97770153
  0.16113716 0.08538493 0.239646   0.96743544]
 [0.70248473 0.96440384 0.27694815 0.70325303 0.24758962 0.27634772
  0.65331799 0.325617   0.19680907 0.7395447 ]
 [0.52894844 0.68951732 0.6846367  0.92152094 0.53018591 0.07615343
  0.46788582 0.43340148 0.88162371 0.39566022]
 [0.82786539 0.75778986 0.3077091  0.430417   0.17347876 0.12336812


5. Create a 3x3x3 array with random values.

In [6]:

random_array = np.random.random((3, 3, 3))
print("Random:", random_array)

Random: [[[0.64473496 0.88427642 0.5417012 ]
  [0.45960128 0.29512606 0.86949107]
  [0.53837651 0.90218154 0.24958653]]

 [[0.70945759 0.50743413 0.7975106 ]
  [0.81522124 0.16484156 0.68364905]
  [0.79348667 0.05785366 0.74860372]]

 [[0.80569568 0.89570245 0.50021941]
  [0.83797475 0.2222001  0.2602242 ]
  [0.92598913 0.17193382 0.47488359]]]


6. Create a random vector of size 30 and find the mean value.

In [8]:
vector_30 = np.random.random(30)
mean_val = np.mean(vector_30)
print("Ran_Vector_30:", vector_30)
print("Mean_val:", mean_val)

Ran_Vector_30: [0.90724779 0.51362314 0.1440291  0.0991281  0.99117909 0.18690025
 0.31421022 0.65739322 0.73763077 0.16227746 0.62924358 0.3117101
 0.94102274 0.41370619 0.40540713 0.41241236 0.65087629 0.71890483
 0.1731198  0.3777915  0.74723022 0.00350518 0.35931856 0.64521033
 0.77810771 0.81479605 0.92564879 0.28150483 0.30951767 0.85453319]
Mean_val: 0.5155728729430856


7. Normalize a 5x5 random matrix.

In [9]:
matrix_5x5 = np.random.random((5, 5))
norm_mat = (matrix_5x5 - np.min(matrix_5x5)) / (np.max(matrix_5x5) - np.min(matrix_5x5))
print("\nNorm_Mat:\n", norm_mat)


Norm_Mat:
 [[0.71169908 0.34662964 0.21374952 0.7935317  0.05929783]
 [0.3785717  0.88408241 0.02858149 1.         0.94734766]
 [0.31760277 0.71695979 0.11078447 0.05382993 0.37643987]
 [0.         0.68187599 0.05476557 0.40559683 0.90841581]
 [0.80456914 0.83590086 0.00544069 0.36150475 0.28455104]]


8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [10]:
mat_5x3 = np.random.random((5, 3))
mat_3x2 = np.random.random((3, 2))
result = np.dot(mat_5x3, mat_3x2)
print("real_mat:", result)

real_mat: [[1.10213016 0.45878807]
 [0.85315255 0.33304802]
 [1.3772659  0.5551743 ]
 [0.66410129 0.27115188]
 [2.07235638 0.86783581]]


9. Create two 3x3 matrices and compute their dot product.
10. Given a 4x4 matrix, find its transpose.
11. Create a 3x3 matrix and calculate its determinant.
12. Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).
13. Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.
14. Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.
15. Given a 5x5 matrix, find the row-wise and column-wise sums.

In [14]:

mat_A = np.random.random((3, 3))
mat_B = np.random.random((3, 3))
dot_product = np.dot(mat_A, mat_B)
print("Dot Product:", dot_product)

matrix_4x4 = np.random.random((4, 4))
transp_matrix = matrix_4x4.T
print("Transp:", transp_matrix)

matrix_3x3 = np.random.random((3, 3))
det = np.linalg.det(matrix_3x3)
print("Determinant:", det)

mat_A_3x4 = np.random.random((3, 4))
mat_B_4x3 = np.random.random((4, 3))
matrix_product = np.dot(mat_A_3x4, mat_B_4x3)
print("Matrix Product of A (3x4) and B (4x3):", matrix_product)

mat_3x3 = np.random.random((3, 3))
vec = np.random.random(3)
mat_vec_prd = np.dot(mat_3x3, vec)
print("Matrix-Vector:", mat_vec_prd)

A = np.random.random((3, 3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print("Javob:", x)

mat = np.random.random((5, 5))
row_sum = np.sum(mat, axis=1)
column_sum = np.sum(mat, axis=0)
print("stroka:", row_sum)
print("stolbtsi:\n", column_sum)


Dot Product: [[0.76187191 0.87528845 0.89385642]
 [0.67373748 0.98244672 1.17503009]
 [0.74855861 0.5302384  0.60537453]]
Transp: [[0.86781768 0.38426544 0.89523533 0.94481791]
 [0.14967748 0.63533466 0.40878789 0.4220874 ]
 [0.98134846 0.35862673 0.30965136 0.87082986]
 [0.70686264 0.99446237 0.29230648 0.56282566]]
Determinant: 0.012213889677995787
Matrix Product of A (3x4) and B (4x3): [[0.1966094  0.65904477 0.32128844]
 [0.45253406 0.5157855  0.39701825]
 [1.0779348  1.09112079 0.97191564]]
Matrix-Vector: [0.28611378 0.55702443 0.76960411]
Javob: [-0.13747574  0.69715145  0.20271102]
stroka: [2.57770379 2.79303731 2.60713257 2.16680799 1.51446203]
stolbtsi:
 [2.08457632 3.0539801  2.749491   2.08657626 1.68452   ]
