Task 1. Write a Python function that converts a temperature from Fahrenheit to Celsius. Use `numpy.vectorize` to apply this function to an array of temperatures: `[32, 68, 100, 212, 77]`. 
   - Formula: $C = (F - 32) \times \frac{5}{9}$

---

Task 2. Create a custom function that takes two arguments: a number and a power. Use `numpy.vectorize` to calculate the power for each pair of numbers in two arrays: `[2, 3, 4, 5]` and `[1, 2, 3, 4]`.

---

Task 3. Solve the system of equations using `numpy`:

$$
\begin{cases}
4x + 5y + 6z = 7 \\
3x - y + z = 4 \\
2x + y - 2z = 5
\end{cases}
$$

---

Task 4. Given the electrical circuit equations below, solve for $I_1, I_2, I_3$ (currents in the branches):

$$
\begin{cases}
10I_1 - 2I_2 + 3I_3 = 12 \\
-2I_1 + 8I_2 - I_3 = -5 \\
3I_1 - I_2 + 6I_3 = 15
\end{cases}
$$

In [75]:
import numpy as np

In [76]:
# Task_1
def fahrenheit_to_celsius(temperature_fahr):
    temperature_cels = (temperature_fahr - 32) * 5 / 9
    return temperature_cels

list_of_fahrenheit = np.array([32, 68, 100, 212, 77])

vect_func = np.vectorize(fahrenheit_to_celsius)
temps_celsius = vect_func(list_of_fahrenheit)


In [77]:
# Task_2
def power_func(num, pow):
    return num**pow
vect_power = np.vectorize(power_func)
num_list = np.array([2, 3, 4, 5])
pow_list = np.array([1, 2, 3, 4])
print(list(vect_power(num_list, pow_list)))

[2, 9, 64, 625]


In [78]:
# Task_3
A = np.array([[4, 5, 6], [3, -1, 1], [2, 1, -2]])
b = np.array([7, 4, 5])

print(list(np.round(np.linalg.solve(A, b))))

[2.0, 1.0, -0.0]


In [79]:
# Task_4
A2 = np.array([[10, -2, 3], [-2, 8, -1], [3, -1, 6]])
b2 = np.array([12, -5, 15])

print(list(np.round(np.linalg.solve(A2, b2), 2)))


[0.49, -0.23, 2.22]


**Image Manipulation with NumPy and PIL**

Image file: `images/birds.jpg`. Your task is to perform the following image manipulations using the **NumPy** library while leveraging **PIL** for reading and saving the image.

**Instructions:**

1. **Flip the Image**:
   - Flip the image horizontally and vertically (left-to-right and up-to-down).

2. **Add Random Noise**:
   - Add random noise to the image.

3. **Brighten Channels**:
   - Increase the brightness of the channels (r.g. red channel) by a fixed value (e.g., 40). Clip the values to ensure they stay within the 0 to 255 range.

4. **Apply a Mask**:
   - Mask a rectangular region in the image (e.g., a 100x100 area in the center) by setting all pixel values in this region to black (0, 0, 0).

**Requirements:**
- Use the **PIL** module onyl to:
  - Read the image.
  - Convert numpy array to image.
  - Save the modified image back to a file.
- Perform all manipulations using NumPy functions. Avoid using image editing functions from PIL or other libraries.


**Bonus Challenge**:
- Create a function for each manipulation (e.g., `flip_image`, `add_noise`, `brighten_channels`, `apply_mask`) to promote modularity and reusability of code.

--- 

In [80]:
from PIL import Image

In [81]:
image = Image.open('birds.jpg')
image_array = np.array(image)

In [82]:
print(image_array.shape)
print(image_array.size)
print(image_array)

(720, 720, 3)
1555200
[[[ 34  98   2]
  [ 34  98   2]
  [ 34  98   2]
  ...
  [ 40  75  19]
  [ 40  75  19]
  [ 40  75  19]]

 [[ 34  98   2]
  [ 34  98   2]
  [ 34  98   2]
  ...
  [ 37  72  16]
  [ 37  72  16]
  [ 37  72  16]]

 [[ 34  98   2]
  [ 34  98   2]
  [ 34  98   2]
  ...
  [ 35  70  14]
  [ 35  70  14]
  [ 35  70  14]]

 ...

 [[ 21  75   0]
  [ 21  75   0]
  [ 21  75   0]
  ...
  [144 110 111]
  [139 105 106]
  [137 103 104]]

 [[ 21  75   0]
  [ 21  75   0]
  [ 21  75   0]
  ...
  [147 113 112]
  [141 107 106]
  [138 104 103]]

 [[ 21  75   0]
  [ 21  75   0]
  [ 21  75   0]
  ...
  [151 117 116]
  [145 111 110]
  [143 109 108]]]


In [83]:
def flip_image(img_array):
    flipped_image = np.flipud(np.fliplr(img_array))
    return flipped_image

In [84]:
def make_brighter(img_array, bright_value=96):
    img_array = img_array.astype(np.int32)
    img_array[:,:,0] += bright_value
    img_array = np.clip(img_array, 0, 255).astype(np.uint8)
    return img_array

In [85]:
def make_mask(img_array, mask_size=(200, 150)):
    height, width, _ = img_array.shape
    center = (height // 2, width // 2)
    mask_cord = (center[0] - mask_size[0] // 2, center[1] - mask_size[1] // 2)
    img_array[mask_cord[0]:mask_cord[0] + mask_size[0], mask_cord[1]:mask_cord[1] + mask_size[1]] = 0
    return img_array

In [86]:
def main():
    flipped_image = flip_image(image_array)
    Image.fromarray(flipped_image).save('flipped_image.jpg')

    brightened_image = make_brighter(image_array)
    Image.fromarray(brightened_image).save('brightened_image.jpg')

    masked_image = make_mask(image_array)
    Image.fromarray(masked_image).save('masked_image.jpg')

In [87]:
if __name__ == '__main__':
    main()